# Generated by Django 5.1.1 on 2025-02-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('ResultAwaiting', 'Result Awaiting'), ('Expelled', 'Expelled')], default='ResultAwaiting', max_length=20)),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='programs.program')),
            ],
        ),
    ]
