mock_programs = [
    {"program_code": "MECH101", "program_name": "Mechanical Engineering"},
    {"program_code": "LAW101", "program_name": "Law"},
    {"program_code": "FIN101", "program_name": "MSc Finance"},
    {"program_code": "DS101", "program_name": "Data Science"},
    {"program_code": "CS101", "program_name": "Computer Science"},
]

mock_users = [
    {
        "username": "sundaresh",
        "email": "sundaresh@example.com",
        "password": "student123",
        "role": "Student",
        "first_name": "Sundaresh",
        "last_name": "Bafna",
        "program_code": "MECH101"
    },
    {
        "username": "profpatrick",
        "email": "patrick@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Patrick",
        "last_name": "Harkness",
        "program_code": "MECH101"
    },
    {
        "username": "profstuart",
        "email": "stuart@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Stuart",
        "last_name": "Grey",
        "program_code": "MECH101"
    },
    {
        "username": "profdezong",
        "email": "dezong@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Dezong",
        "last_name": "Zhao",
        "program_code": "MECH101"
    },
    {
        "username": "profsmith",
        "email": "smith@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "John",
        "last_name": "Smith",
        "program_code": "MECH101"
    },
    {
        "username": "prem",
        "email": "prem@example.com",
        "password": "student123",
        "role": "Student",
        "first_name": "Prem",
        "last_name": "Thalapathy",
        "program_code": "LAW101"
    },
    {
        "username": "drjames",
        "email": "drjames@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "James",
        "last_name": "Devaney",
        "program_code": "LAW101"
    },
    {
        "username": "profkonstantinos",
        "email": "konstantinos@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Konstantinos",
        "last_name": "Sergakis",
        "program_code": "LAW101"
    },
    {
        "username": "drzinian",
        "email": "drzinian@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Zinian",
        "last_name": "Zhang",
        "program_code": "LAW101"
    },
    {
        "username": "shruthi",
        "email": "shruthi@example.com",
        "password": "student123",
        "role": "Student",
        "first_name": "Shruthi",
        "last_name": "Unknown",
        "program_code": "FIN101"
    },
    {
        "username": "profbart",
        "email": "bart@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Bart",
        "last_name": "Taub",
        "program_code": "FIN101"
    },
    {
        "username": "profcarsten",
        "email": "carsten@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Carsten",
        "last_name": "Sprenger",
        "program_code": "FIN101"
    },
    {
        "username": "profzafer",
        "email": "zafer@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Zafer",
        "last_name": "Kanik",
        "program_code": "FIN101"
    },
    {
        "username": "adhi",
        "email": "adhi@example.com",
        "password": "student123",
        "role": "Student",
        "first_name": "Adithyan",
        "last_name": "Annadurai",
        "program_code": "DS101"
    },
    {
        "username": "profnikela",
        "email": "nikela.papa@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Nikela",
        "last_name": "Papadopoulou",
        "program_code": "DS101"
    },
    {
        "username": "profemma",
        "email": "emma.li@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Emma",
        "last_name": "Li",
        "program_code": "DS101"
    },
    {
        "username": "profjoemon",
        "email": "joemon.jose@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Joemon",
        "last_name": "Jose",
        "program_code": "DS101"
    },
    {
        "username": "profrichard",
        "email": "richard.mccreadie@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Richard",
        "last_name": "McCreadie",
        "program_code": "DS101"
    },
    {
        "username": "profsean",
        "email": "sean.macavaney@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Sean",
        "last_name": "MacAvaney",
        "program_code": "DS101"
    },
    {
        "username": "profkevin",
        "email": "kevin.bryson@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Kevin",
        "last_name": "Bryson",
        "program_code": "DS101"
    },
    {
        "username": "mockstudent",
        "email": "student@example.com",
        "password": "student123",
        "role": "Student",
        "first_name": "John",
        "last_name": "Doe",
        "program_code": "CS101"
    },
    {
        "username": "mockprofessor",
        "email": "professor@example.com",
        "password": "professor123",
        "role": "Professor",
        "first_name": "Alice",
        "last_name": "Smith",
        "program_code": "CS101"
    },
    {
        "username": "mockadmin",
        "email": "admin@example.com",
        "password": "admin123",
        "role": "Admin",
        "first_name": "Robert",
        "last_name": "Brown",
    },
]

mock_courses = [
    {
        "course_code": "VIB101",
        "course_name": "Vibration",
        "program_code": "MECH101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profpatrick",   
    },
    {
        "course_code": "IED102",
        "course_name": "Integrated Engineering Design",
        "program_code": "MECH101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profstuart",
    },
    {
        "course_code": "AVG103",
        "course_name": "Auto Vehicle Guidance Systems",
        "program_code": "MECH101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profdezong",
    },
    {
        "course_code": "ATE104",
        "course_name": "Advanced Thermal Engineering 5",
        "program_code": "MECH101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profsmith",
    },
    {
        "course_code": "ESM105",
        "course_name": "Engineering Skills M",
        "program_code": "MECH101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profsmith",
    },
    {
        "course_code": "IIL101",
        "course_name": "International Investment Law",
        "program_code": "LAW101",
        "semester_number": 2,
        "course_type": "Seminar",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "drjames",
    },
    {
        "course_code": "ICM102",
        "course_name": "International Capital Markets",
        "program_code": "LAW101",
        "semester_number": 2,
        "course_type": "Seminar",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profkonstantinos",
    },
    {
        "course_code": "IIL103",
        "course_name": "International Insolvency Law",
        "program_code": "LAW101",
        "semester_number": 2,
        "course_type": "Seminar",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "drjames",
    },
    {
        "course_code": "EFM101",
        "course_name": "Econ Fundamentals/Fin Markets",
        "program_code": "FIN101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profbart",
    },
    {
        "course_code": "CFI102",
        "course_name": "Corporate Finance and Investment",
        "program_code": "FIN101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profcarsten",
    },
    {
        "course_code": "MBF103",
        "course_name": "Modern Banking Theory",
        "program_code": "FIN101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profzafer",
    },
    {
        "course_code": "CSF101",
        "course_name": "Cyber Security Fundamentals",
        "program_code": "DS101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profemma",
    },
    {
        "course_code": "WS102",
        "course_name": "Web Science for MSc",
        "program_code": "DS101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profjoemon",
    },
    {
        "course_code": "BD103",
        "course_name": "Big Data (M)",
        "program_code": "DS101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profrichard",
    },
    {
        "course_code": "TD104",
        "course_name": "Text as Data for MSc",
        "program_code": "DS101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profsean",
    },
    {
        "course_code": "IT105",
        "course_name": "Internet Technology (M)",
        "program_code": "DS101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profnikela",
    },
    {
        "course_code": "DL106",
        "course_name": "Deep Learning MSc (M)",
        "program_code": "DS101",
        "semester_number": 2,
        "course_type": "Lecture",
        "credits": 3,
        "academic_year_added": 2025,
        "professor_username": "profkevin",
    },
    {
        "course_code": "CS201",
        "course_name": "Machine Learning",
        "program_code": "CS101",
        "semester_number": 2,
        "course_type": "Mandatory",
        "credits": 3,
        "academic_year_added": 2024,
        "professor_username": "mockprofessor"
    },
    {
        "course_code": "CS202",
        "course_name": "Web Science",
        "program_code": "CS101",
        "semester_number": 3,
        "course_type": "Mandatory",
        "credits": 4,
        "academic_year_added": 2024,
        "professor_username": "mockprofessor"
    },
]

mock_enrollments = [
    {
        "student_username": "sundaresh",
        "course_code": "VIB101",
        "created_by": "mockadmin",
    },
    {
        "student_username": "sundaresh",
        "course_code": "IED102",
        "created_by": "mockadmin",
    },
    {
        "student_username": "sundaresh",
        "course_code": "AVG103",
        "created_by": "mockadmin",
    },
    {
        "student_username": "sundaresh",
        "course_code": "ATE104",
        "created_by": "mockadmin",
    },
    {
        "student_username": "sundaresh",
        "course_code": "ESM105",
        "created_by": "mockadmin",
    },
    {"student_username": "prem", "course_code": "IIL101", "created_by": "mockadmin"},
    {"student_username": "prem", "course_code": "ICM102", "created_by": "mockadmin"},
    {"student_username": "prem", "course_code": "IIL103", "created_by": "mockadmin"},
    {"student_username": "shruthi", "course_code": "EFM101", "created_by": "mockadmin"},
    {"student_username": "shruthi", "course_code": "CFI102", "created_by": "mockadmin"},
    {"student_username": "shruthi", "course_code": "MBF103", "created_by": "mockadmin"},
    {"student_username": "adhi", "course_code": "CSF101", "created_by": "mockadmin"},
    {"student_username": "adhi", "course_code": "WS102", "created_by": "mockadmin"},
    {"student_username": "adhi", "course_code": "BD103", "created_by": "mockadmin"},
    {"student_username": "adhi", "course_code": "TD104", "created_by": "mockadmin"},
    {"student_username": "adhi", "course_code": "IT105", "created_by": "mockadmin"},
    {"student_username": "adhi", "course_code": "DL106", "created_by": "mockadmin"},
    {
        "student_username": "mockstudent",
        "course_code": "CS201",
        "created_by": "mockadmin",
    },
    {
        "student_username": "mockstudent",
        "course_code": "CS202",
        "created_by": "mockadmin",
    },
]


mock_grades = [
    {
        "student_username": "sundaresh",
        "course_code": "VIB101",
        "professor_username": "profpatrick",
        "grade": "A-",
        "comments": "Good understanding of vibrations.",
    },
    {
        "student_username": "sundaresh",
        "course_code": "IED102",
        "professor_username": "profstuart",
        "grade": "B+",
        "comments": "Great approach to engineering design.",
    },
    {
        "student_username": "sundaresh",
        "course_code": "AVG103",
        "professor_username": "profdezong",
        "grade": "A",
        "comments": "Excellent work in vehicle guidance systems.",
    },
    {
        "student_username": "sundaresh",
        "course_code": "ATE104",
        "professor_username": "profsmith",
        "grade": "B",
        "comments": "Needs more work on thermal concepts.",
    },
    {
        "student_username": "sundaresh",
        "course_code": "ESM105",
        "professor_username": "profsmith",
        "grade": "A",
        "comments": "Strong skills in engineering practices.",
    },
    {
        "student_username": "prem",
        "course_code": "IIL101",
        "professor_username": "drjames",
        "grade": "A",
        "comments": "Excellent understanding of investment law.",
    },
    {
        "student_username": "prem",
        "course_code": "ICM102",
        "professor_username": "profkonstantinos",
        "grade": "B+",
        "comments": "Good grasp of international capital markets.",
    },
    {
        "student_username": "prem",
        "course_code": "IIL103",
        "professor_username": "drzinian",
        "grade": "A-",
        "comments": "Well-structured arguments in insolvency law discussions.",
    },
    {
        "student_username": "shruthi",
        "course_code": "EFM101",
        "professor_username": "profbart",
        "grade": "A",
        "comments": "Strong grasp of economic fundamentals.",
    },
    {
        "student_username": "shruthi",
        "course_code": "CFI102",
        "professor_username": "profcarsten",
        "grade": "B+",
        "comments": "Good understanding of corporate finance.",
    },
    {
        "student_username": "shruthi",
        "course_code": "MBF103",
        "professor_username": "profzafer",
        "grade": "A-",
        "comments": "Excellent analytical skills in banking theory.",
    },
    {
        "student_username": "adhi",
        "course_code": "CSF101",
        "professor_username": "profemma",
        "grade": "A",
        "comments": "Excellent cybersecurity skills.",
    },
    {
        "student_username": "adhi",
        "course_code": "WS102",
        "professor_username": "profjoemon",
        "grade": "A-",
        "comments": "Good knowledge of Web Science.",
    },
    {
        "student_username": "adhi",
        "course_code": "BD103",
        "professor_username": "profrichard",
        "grade": "B+",
        "comments": "Well-structured analysis in Big Data.",
    },
    {
        "student_username": "adhi",
        "course_code": "TD104",
        "professor_username": "profsean",
        "grade": "A",
        "comments": "Excellent text data analysis.",
    },
    {
        "student_username": "adhi",
        "course_code": "DL106",
        "professor_username": "profkevin",
        "grade": "A",
        "comments": "Strong understanding of deep learning concepts.",
    },
    {
        "student_username": "mockstudent",
        "course_code": "CS201",
        "professor_username": "mockprofessor",
        "grade": "A",
        "comments": "Excellent work",
    },
    {
        "student_username": "mockstudent",
        "course_code": "CS202",
        "professor_username": "mockprofessor",
        "grade": "B",
        "comments": "Good effort",
    },
]

mock_schedules = [
    {
        "academic_year": "2024-2025",
        "course_code": "VIB101",
        "professor_username": "profpatrick",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-11T10:00:00Z",
        "schedule_end": "2025-03-11T11:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU;BYHOUR=10;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "IED102",
        "professor_username": "profstuart",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-11T11:00:00Z",
        "schedule_end": "2025-03-11T12:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU;BYHOUR=11;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "AVG103",
        "professor_username": "profdezong",
        "is_scheduled": True,
        "is_online": True,
        "schedule_start": "2025-03-11T16:00:00Z",
        "schedule_end": "2025-03-11T17:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU;BYHOUR=16;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "VIB101",
        "professor_username": "profpatrick",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-12T12:00:00Z",
        "schedule_end": "2025-03-12T13:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=WE;BYHOUR=12;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "IED102",
        "professor_username": "profsmith",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-13T09:00:00Z",
        "schedule_end": "2025-03-13T12:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TH;BYHOUR=9;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "ATE104",
        "professor_username": "profsmith",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-13T15:00:00Z",
        "schedule_end": "2025-03-13T17:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TH;BYHOUR=15;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "IIL101",
        "professor_username": "drjames",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-10T09:00:00Z",
        "schedule_end": "2025-03-10T11:00:00Z",
        "course_type": "Seminar",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=MO;BYHOUR=9;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "ICM102",
        "professor_username": "profkonstantinos",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-11T15:00:00Z",
        "schedule_end": "2025-03-11T17:00:00Z",
        "course_type": "Seminar",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU;BYHOUR=15;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "IIL103",
        "professor_username": "drzinian",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-14T13:00:00Z",
        "schedule_end": "2025-03-14T15:00:00Z",
        "course_type": "Seminar",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=FR;BYHOUR=13;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "EFM101",
        "professor_username": "profbart",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-11T09:00:00Z",
        "schedule_end": "2025-03-11T11:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU;BYHOUR=9;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "CFI102",
        "professor_username": "profcarsten",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-10T09:00:00Z",
        "schedule_end": "2025-03-10T11:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=MO;BYHOUR=9;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "MBF103",
        "professor_username": "profzafer",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-13T17:00:00Z",
        "schedule_end": "2025-03-13T19:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TH;BYHOUR=17;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "CSF101",
        "professor_username": "profemma",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-17T09:00:00Z",
        "schedule_end": "2025-03-17T10:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=MO;BYHOUR=9;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "WS102",
        "professor_username": "profjoemon",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-17T11:00:00Z",
        "schedule_end": "2025-03-17T13:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=MO;BYHOUR=11;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "BD103",
        "professor_username": "profrichard",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-17T13:00:00Z",
        "schedule_end": "2025-03-17T15:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=MO;BYHOUR=13;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "TD104",
        "professor_username": "profsean",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-18T09:00:00Z",
        "schedule_end": "2025-03-18T10:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU;BYHOUR=9;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "IT105",
        "professor_username": "profnikela",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-18T16:00:00Z",
        "schedule_end": "2025-03-18T17:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU;BYHOUR=16;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "DL106",
        "professor_username": "profkevin",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2025-03-21T09:00:00Z",
        "schedule_end": "2025-03-21T10:00:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=FR;BYHOUR=9;BYMINUTE=0;BYSECOND=0",
    },
    {
        "academic_year": "2024-2025",
        "course_code": "CS201",
        "professor_username": "mockprofessor",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2024-09-01T09:00:00Z",
        "schedule_end": "2024-09-01T10:30:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=TU,TH;BYHOUR=9;BYMINUTE=0;BYSECOND=0",  # Every Tuesday and Thursday at 9 AM
    },
    {
        "academic_year": "2024-2025",
        "course_code": "CS202",
        "professor_username": "mockprofessor",
        "is_scheduled": True,
        "is_online": False,
        "schedule_start": "2024-09-02T11:00:00Z",
        "schedule_end": "2024-09-02T12:30:00Z",
        "course_type": "Lecture",
        "created_by": "mockadmin",
        "recurrence_rule": "FREQ=WEEKLY;BYDAY=MO,WE;BYHOUR=11;BYMINUTE=0;BYSECOND=0",  # Every Monday and Wednesday at 11 AM
    },
]