# Generated by Django 5.1.1 on 2025-02-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('semester_number', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Elective', 'Elective')], max_length=20)),
                ('academic_year_added', models.CharField(max_length=10)),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='programs.program')),
            ],
        ),
    ]
