# Generated by Django 5.1.1 on 2025-02-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('professors', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='program_code',
            new_name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_taught', to='professors.professor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year_added',
            field=models.PositiveIntegerField(),
        ),
    ]
