# Generated by Django 5.1.1 on 2025-02-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Admin', 'Admin'), ('Guest', 'Guest')], default='Guest', max_length=20),
        ),
    ]
