# Generated by Django 5.1.1 on 2025-02-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mockuser_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Student', 'Student'), ('Professor', 'Professor'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
