# Generated by Django 5.1.1 on 2025-02-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_program_code_course_program_course_credits_and_more'),
        ('professors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='courses_taught', to='professors.professor'),
        ),
    ]
