# Generated by Django 5.1.1 on 2025-02-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_time',
            new_name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default='No reason provided'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
