# Generated by Django 5.1.1 on 2025-02-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('schedule_start', models.DateTimeField()),
                ('schedule_end', models.DateTimeField()),
                ('recurrence_rule', models.TextField(blank=True, null=True)),
                ('course_type', models.CharField(choices=[('Lab', 'Lab'), ('Lecture', 'Lecture')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
            ],
        ),
    ]
