# Generated by Django 5.1.1 on 2025-02-28 14:32

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_courseschedule_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='recurrence_rule',
            field=recurrence.fields.RecurrenceField(default=''),
        ),
    ]
