# Generated by Django 5.1.1 on 2025-03-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_courseschedule_recurrence_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
